source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ITDAvatarPlaceholder_Example' do
  pod 'ITDAvatarPlaceholder', :path => '../'
end

target 'ITDAvatarPlaceholder_Tests' do
  pod 'ITDAvatarPlaceholder', :path => '../'
end
